export default [
    {
        id: 1,
        title: "Fadó Irish Pub",
        address: "4022 Townsfair Way, Columbus, OH 43219",
        description: "This cozy pub has decor imported from Ireland & a traditional menu that includes all-day breakfast.",
        hours: "7:30 AM to 9:00 PM",
        phone: "(614) 418-0066",
        rating: 4.5,
        img: "pub_fado.jpg",
    },
    
    {
        id: 3,
        title: "Mac's Proper Pub",
        address: "693 N High St, Columbus, OH 43215",
        description: "Comfortable Scottish-themed pub with American burgers & beers, plus Scotch eggs & sauerkraut balls.",
        hours: "12:00 PM to 12:00 AM",
        phone: "(614) 221-6227",
        rating: 4.4,
        img: "pub_mac.jpg",
    },
    {
        id: 4,
        title: "Donericks Pub House",
        address: "693 N High St, Columbus, OH 43215",
        description: "Comfortable Scottish-themed pub with American burgers & beers, plus Scotch eggs & sauerkraut balls.",
        hours: "11:00 AM to 2:30 AM",
        phone: "(614) 575-9811",
        rating: 4.1,
        img: "pub_don.jpg",
    },
    {
        id: 5,
        title: "Byrne's House",
        address: "1248 W 3rd Ave, Columbus, OH 43212",
        description: "Convivial family-run Irish pub offering hearty bar food, darts leagues & regular live music.",
        hours: "12:00 PM to 12:00 AM",
        phone: "(614) 486-4722",
        rating: 4.6,
        img: "pub_byrne.jpg",
    },
    {
        id: 6,
        title: "O'Reilly's Pub",
        address: "2822 N High St, Columbus, OH 43202",
        description: "Casual neighborhood hangout, offering up hearty American fare, drinks & the big game on TV.",
        hours: "11:00 AM to 2:30 AM",
        phone: "(614) 262-6343",
        rating: 4.5,
        img: "pub_reilly.jpg",
    },
    {
        id: 7,
        title: "Turtle Creek Tavern",
        address: "5571 N Hamilton Rd, Columbus, OH 43230",
        description: "Easygoing hot spot offering outdoor seating, pub grub, live music & sports on the TVs.",
        hours: "11:00 AM to 2:30 AM",
        phone: "(614) 476-8836",
        rating: 4.5,
        img: "pub_turtle.jpg",
    },
    {
        id: 2,
        title: "Hamilton's Pub",
        address: "4866 Thompson Rd, Columbus, OH 43230",
        description: "Pub fare & draft beer in a modern space with sports on flat-screens, frequent live bands & a patio.",
        hours: "11:30 AM to 2:00 AM",
        phone: "(614) 775-0007",
        rating: 4.2,
        img: "pub_hamilton.jpg",
    },

]